export default {
	"title": undefined,
	"field": undefined,
	"columns": undefined,
	"visible": undefined,
	"hozAlign": undefined,
	"vertAlign": undefined,
	"width": undefined,
	"minWidth": 40,
	"maxWidth": undefined,
	"tooltip": undefined,
	"cssClass": undefined,

	"print": undefined,
	"htmlOutput": undefined,
	"sorter": undefined,
	"sorterParams": undefined,
	"formatter": undefined,
	"formatterParams": undefined,
	"variableHeight": undefined,
	"editable": undefined,
	"editor": undefined,
	"editorParams": undefined,
	"validator": undefined,

	"clipboard": undefined,
	"download": undefined,

	"cellClick": undefined,
	"cellDblClick": undefined,
	"cellContext": undefined,
	"cellTap": undefined,
	"cellDblTap": undefined,
	"cellTapHold": undefined,
	"cellMouseEnter": undefined,
	"cellMouseLeave": undefined,
	"cellMouseOver": undefined,
	"cellMouseOut": undefined,
	"cellMouseMove": undefined,
	"cellEditing": undefined,
	"cellEdited": undefined,
	"cellEditCancelled": undefined,
	"headerSort": undefined,
	"headerSortStartingDir": undefined,
	"headerSortTristate": undefined,
	"headerClick": undefined,
	"headerDblClick": undefined,
	"headerContext": undefined,
	"headerMouseEnter": undefined,
	"headerMouseLeave": undefined,
	"headerMouseOver": undefined,
	"headerMouseOut": undefined,
	"headerMouseMove": undefined,
	"headerTap": undefined,
	"headerDblTap": undefined,
	"headerTapHold": undefined,
	"headerTapHold": undefined,
	"headerTooltip": undefined,
	"headerVertical": undefined,
	"headerHozAlign": undefined,
	"editableTitle": undefined,
	"titleFormatter": undefined,
	"titleFormatterParams": undefined,

	"print": undefined,

	"titlePrint": undefined,
	"titleClipboard": undefined,
	"titleHtmlOutput": undefined,
	"titleDownload": undefined,
}