export default {
	navPrev:"shift + 9",
	navNext:9,
	navUp:38,
	navDown:40,
	navLeft:37,
	navRight:39,
	scrollPageUp:33,
	scrollPageDown:34,
	scrollToStart:36,
	scrollToEnd:35,
	undo:["ctrl + 90", "meta + 90"],
	redo:["ctrl + 89", "meta + 89"],
	copyToClipboard:["ctrl + 67", "meta + 67"],

	spreadsheetJumpUp:["ctrl + 38", "meta + 38"],
	spreadsheetJumpDown:["ctrl + 40", "meta + 40"],
	spreadsheetJumpLeft:["ctrl + 37", "meta + 37"],
	spreadsheetJumpRight:["ctrl + 39", "meta + 39"],
	spreadsheetExpandUp:"shift + 38",
	spreadsheetExpandDown:"shift + 40",
	spreadsheetExpandLeft:"shift + 37",
	spreadsheetExpandRight:"shift + 39",
	spreadsheetExpandJumpUp:["ctrl + shift + 38", "meta + shift + 38"],
	spreadsheetExpandJumpDown:["ctrl + shift + 40", "meta + shift + 40"],
	spreadsheetExpandJumpLeft:["ctrl + shift + 37", "meta + shift + 37"],
	spreadsheetExpandJumpRight:["ctrl + shift + 39", "meta + shift + 39"],
	spreadsheetEditCell:13,
};
