export default {
	navPrev:"shift + 9",
	navNext:9,
	navUp:38,
	navDown:40,
	navLeft:37,
	navRight:39,
	navUpAlt:["ctrl + 38", "meta + 38"],
	navDownAlt:["ctrl + 40", "meta + 40"],
	navLeftAlt:["ctrl + 37", "meta + 37"],
	navRightAlt:["ctrl + 39", "meta + 39"],
	expandUp:"shift + 38",
	expandDown:"shift + 40",
	expandLeft:"shift + 37",
	expandRight:"shift + 39",
	expandUpAlt:["ctrl + shift + 38", "meta + shift + 38"],
	expandDownAlt:["ctrl + shift + 40", "meta + shift + 40"],
	expandLeftAlt:["ctrl + shift + 37", "meta + shift + 37"],
	expandRightAlt:["ctrl + shift + 39", "meta + shift + 39"],
	scrollPageUp:33,
	scrollPageDown:34,
	scrollToStart:36,
	scrollToEnd:35,
	undo:["ctrl + 90", "meta + 90"],
	redo:["ctrl + 89", "meta + 89"],
	copyToClipboard:["ctrl + 67", "meta + 67"],
};